steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: asia-southeast1-docker.pkg.dev/REPLACE_PROJECT_ID/sweet-house/sweet-house:manual

