window.addEventListener("DOMContentLoaded", () => {
  const params = new URLSearchParams(window.location.search);
  const shopIdNode = document.querySelector("#shopeeShopId");
  const statusNode = document.querySelector("#shopeeBatchStatus");
  const ordersNode = document.querySelector("#shopeeShipmentOrders");
  const choicesNode = document.querySelector("#shopeeBatchChoices");
  const selectedIds = new Set((params.get("orderIds") || "").split(",").filter(Boolean));
  shopIdNode.value = params.get("shopId") || localStorage.getItem("shopeeShopId") || "";
  const state = { orders: [], batches: [], selections: new Map(), previews: [] };
  const escapeHtml = (value) => String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
  const api = async (route, options = {}) => { const request = { ...options, headers: { ...(options.headers || {}) } }; if (request.body && typeof request.body !== "string") { request.headers["content-type"] = "application/json"; request.body = JSON.stringify(request.body); } const response = await fetch(route, request); const result = await response.json(); if (!response.ok) throw new Error(result.error || "ดำเนินการ shipment ไม่สำเร็จ"); return result; };
  const shopId = () => { const value = shopIdNode.value.trim(); if (value) localStorage.setItem("shopeeShopId", value); return value; };
  const setStatus = (message, kind = "") => { statusNode.textContent = message; statusNode.className = `status-box active ${kind}`; };
  const selectedOrders = () => state.orders.filter((order) => selectedIds.size === 0 || selectedIds.has(String(order.id)));
  const setButtons = () => { const ready = state.batches.length > 0; document.querySelector("#arrangeShopeeShipmentButton").disabled = !ready; document.querySelector("#refreshShopeeTrackingButton").disabled = !ready; document.querySelector("#createShopeeDocumentsButton").disabled = !ready; document.querySelector("#overlayShopeeLabelsButton").disabled = !ready; document.querySelector("#printShopeeLabelsButton").disabled = state.previews.length === 0; };
  const renderOrders = () => { ordersNode.textContent = selectedOrders().length ? `เลือกไว้ ${selectedOrders().length} orders: ${selectedOrders().map((order) => order.orderNo).join(", ")}` : "ยังไม่มี order ที่เลือก"; };
  const renderBatches = () => { choicesNode.innerHTML = state.batches.map((batch) => { const addresses = batch.pickup?.addresses || []; const selection = state.selections.get(String(batch.id)) || {}; const preview = state.previews.find((item) => String(item.batchId) === String(batch.id)); return `<article class="shopee-batch"><strong>Batch #${escapeHtml(batch.id)} / ${escapeHtml(batch.logisticsChannelId || "")}</strong><label class="field"><span>Pickup address</span><select data-batch-address="${escapeHtml(batch.id)}"><option value="">เลือก address</option>${addresses.map((address) => `<option value="${escapeHtml(address.addressId)}" ${selection.addressId === address.addressId ? "selected" : ""}>${escapeHtml(address.fullAddress || address.addressId)}</option>`).join("")}</select></label><label class="field"><span>Pickup time slot</span><select data-batch-time="${escapeHtml(batch.id)}"><option value="">เลือกเวลา</option>${addresses.flatMap((address) => address.timeSlots || []).map((slot) => `<option value="${escapeHtml(slot.pickupTimeId)}" ${selection.pickupTimeId === slot.pickupTimeId ? "selected" : ""}>${escapeHtml(slot.label || slot.pickupTimeId)}</option>`).join("")}</select></label><div class="muted">สถานะ: ${escapeHtml(batch.status)} / ${batch.orders?.length || 0} packages</div>${preview ? `<a class="button secondary small" href="${escapeHtml(preview.downloadUrl)}" target="_blank" rel="noopener">เปิดใบปะหน้า Custom</a>` : ""}</article>`; }).join(""); setButtons(); };
  async function loadOrders() { if (!shopId()) throw new Error("ระบุ Shop ID ก่อนโหลด order"); const result = await api(`/api/platform-orders?shopId=${encodeURIComponent(shopId())}`); state.orders = result.orders || []; renderOrders(); }
  async function prepare() { const ids = selectedOrders().map((order) => Number(order.id)); if (!ids.length) throw new Error("เลือก order จากหน้า Orders ก่อน"); const result = await api("/api/shopee/shipment-batches/prepare", { method: "POST", body: { connectionId: shopId(), orderIds: ids } }); state.batches = result.batches || []; state.previews = []; renderBatches(); setStatus(`เตรียม ${state.batches.length} batch แล้ว`, "success"); }
  async function arrange() { for (const batch of state.batches) { const selection = state.selections.get(String(batch.id)) || {}; if (!selection.addressId || !selection.pickupTimeId) throw new Error(`เลือก address และเวลาใน Batch #${batch.id}`); await api(`/api/shopee/shipment-batches/${encodeURIComponent(batch.id)}/arrange`, { method: "POST", body: { connectionId: shopId(), selection } }); } await loadOrders(); setStatus("นัดรับสินค้าสำเร็จ รอ Tracking", "success"); }
  async function refreshTracking() { for (const batch of state.batches) await api(`/api/shopee/shipment-batches/${encodeURIComponent(batch.id)}/refresh-tracking`, { method: "POST", body: { connectionId: shopId() } }); await loadOrders(); setStatus("Refresh Tracking แล้ว", "success"); }
  async function createDocuments() { for (const batch of state.batches) { const result = await api(`/api/shopee/shipment-batches/${encodeURIComponent(batch.id)}/create-documents`, { method: "POST", body: { connectionId: shopId() } }); if (result.job?.id) await api(`/api/shopee/shipping-document-jobs/${encodeURIComponent(result.job.id)}/poll`, { method: "POST", body: { connectionId: shopId() } }); } setStatus("ส่งคำขอใบปะหน้าแล้ว", "success"); }
  async function overlayLabels() { const mappings = {}; for (const order of selectedOrders()) { if ((order.lines || []).some((line) => line.mappingStatus !== "mapped" || !line.mappedStockSku)) throw new Error(`ยัง map Stock SKU ไม่ครบใน Order ${order.orderNo}`); mappings[order.id] = { textLines: order.lines.map((line) => `${line.mappedStockSku} × ${line.quantity}`), protectedRegions: [] }; } state.previews = []; for (const batch of state.batches) { const result = await api(`/api/shopee/shipment-batches/${encodeURIComponent(batch.id)}/overlay-labels`, { method: "POST", body: { mappings } }); state.previews.push({ batchId: batch.id, downloadUrl: result.downloadUrl }); } renderBatches(); setStatus("สร้าง Custom Label แบบ batch แล้ว", "success"); }
  const run = (work) => work().catch((error) => setStatus(error.message, "error"));
  document.querySelector("#loadShopeeShipmentOrdersButton").addEventListener("click", () => run(loadOrders));
  document.querySelector("#prepareShopeeShipmentButton").addEventListener("click", () => run(prepare));
  document.querySelector("#arrangeShopeeShipmentButton").addEventListener("click", () => run(arrange));
  document.querySelector("#refreshShopeeTrackingButton").addEventListener("click", () => run(refreshTracking));
  document.querySelector("#createShopeeDocumentsButton").addEventListener("click", () => run(createDocuments));
  document.querySelector("#overlayShopeeLabelsButton").addEventListener("click", () => run(overlayLabels));
  document.querySelector("#printShopeeLabelsButton").addEventListener("click", () => { const first = state.previews[0]; if (first?.downloadUrl) window.open(first.downloadUrl, "_blank", "noopener"); });
  choicesNode.addEventListener("change", (event) => { const address = event.target.closest("[data-batch-address]"); const time = event.target.closest("[data-batch-time]"); const id = address?.dataset.batchAddress || time?.dataset.batchTime; if (!id) return; const selection = state.selections.get(String(id)) || {}; if (address) selection.addressId = address.value; if (time) selection.pickupTimeId = time.value; state.selections.set(String(id), selection); });
  document.querySelector("#backToShopeeMappingButton").href = `/shopee-mapping?shopId=${encodeURIComponent(shopId())}&orderIds=${encodeURIComponent([...selectedIds].join(","))}`;
  run(loadOrders);
});
